/*
 * CGameover.java
 *
 * Created on 2006년 11월 13일 (월), 오후 3:06
 */

package client;

/**
 *
 * @author 신구
 */
public class CGameover extends javax.swing.JPanel {

	/** Creates new form CGameover */
	public CGameover() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc=" Generated Code ">//GEN-BEGIN:initComponents
	private void initComponents() {

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				this);
		// Group 레이아웃 생성
		this.setLayout(layout);
		layout.setHorizontalGroup(
		// 수평 레이아웃
		layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(0, 400, Short.MAX_VALUE));
		layout.setVerticalGroup(
		// 수직 레이아웃
		layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(0, 300, Short.MAX_VALUE));
	}
	// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	// End of variables declaration//GEN-END:variables

}
