package client;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;

import javax.media.bean.playerbean.MediaPlayer;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;

public class CLogin extends javax.swing.JPanel implements ActionListener {
	Main m_main; // 메인변수

	Image m_bg; // 이미지변수

	MediaPlayer m_plogin; // 로그인시 노래 변수

	ImageIcon m_login = new ImageIcon("loginbutton.jpg"); // LOGIN 버튼

	// 로그인 함수
	public void actionPerformed(ActionEvent e) {

		String id; // 플레이어 id

		// 로그인시 아이디입력 필드 옆 로그인 버튼
		if (e.getSource() == jButton1) {
			id = jTextField1.getText(); // id창에 입력된 값을 id로 받는다.

			// 두 문자열비교(기존 아이디와 입력된 새 아이디)
			if (true == id.equalsIgnoreCase("")) {
				/*
				 * try { // 새 아이디 입력의 경우 로그인시 사운드 
				 * SunAudioClip m_loginf = new SunAudioClip ("loginf.wav"); m_loginf.play(); // 로그인하여 플레이
				 *  }
				 * catch(IOException err){;}
				 */
				try {
			        Player p = new Player(new FileInputStream(new File("loginf.wav")));
			        System.out.println("Play");
			        p.play();
			        p.close();
			        System.out.println("Stop");
			    } catch (FileNotFoundException e1) {
			        e1.printStackTrace();
			        System.out.println("Error");
			    } catch (JavaLayerException e1) {
			        e1.printStackTrace();
			        System.out.println("Error");
			    } 
				// 아이디 다시입력
				JOptionPane.showMessageDialog(null, "아이디를 입력하세요", "알림!!",
						JOptionPane.INFORMATION_MESSAGE); // 겹치는 아이디일 경우 표시
				return;
			}

			m_plogin.start(); // 로그인하여 스타트
			m_main.Login(id); // 입력된 아이디로 로그인 한다.
		}
		// 로그인시 아이디입력 필드 창
		if (e.getSource() == jTextField1) {
			id = jTextField1.getText(); // id창에 입력된 값을 id로 받는다.

			// 두 문자열비교(기존 아이디와 입력된 새 아이디)
			if (true == id.equalsIgnoreCase("")) {
				/*
				 * try { // 새 아이디 입력의 경우 로그인시 사운드 SunAudioClip m_loginf = new
				 * SunAudioClip ("loginf.wav"); m_loginf.play(); // 로그인하여 플레이 }
				 * 
				 * catch(IOException err){;}
				 */

				try {
			        Player p = new Player(new FileInputStream(new File("loginf.wav")));
			        System.out.println("Play");
			        p.play();
			        p.close();
			        System.out.println("Stop");
			    } catch (FileNotFoundException e1) {
			        e1.printStackTrace();
			        System.out.println("Error");
			    } catch (JavaLayerException e1) {
			        e1.printStackTrace();
			        System.out.println("Error");
			    } 
				
				// 아이디 다시입력
				JOptionPane.showMessageDialog(null, "아이디를 입력하세요", "알림!!",
						JOptionPane.INFORMATION_MESSAGE); // 겹치는 아이디일 경우 표시
				return;
			}

			m_plogin.start(); // 로그인하여 스타트
			m_main.Login(id); // 입력된 아이디로 로그인한다.
		}
	}

	// 게임 그래픽 함수
	public void paintComponent(Graphics g) {
		g.drawImage(m_bg, 0, 0, this);
	}

	// 로그인 시 필요한 이미지, 사운드 등을 불러오는 함수
	public CLogin(Main m) {

		m_main = m;
		m_bg = Toolkit.getDefaultToolkit().getImage("login.jpg");

		m_plogin = new MediaPlayer();
		m_plogin.setMediaLocation(new java.lang.String("file:login.mp3"));
		m_plogin.setPlaybackLoop(false);

		initComponents();

		jButton1.setIcon(m_login);
		jButton1.addActionListener(this);
		jTextField1.addActionListener(this);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc=" Generated Code ">//GEN-BEGIN:initComponents

	// 게임 창 사이즈 정하는 함수
	private void initComponents() {
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();

		jButton1.setIcon(new javax.swing.ImageIcon(
				"C:\\Documents and Settings\\신구\\바탕 화면\\베네치아\\Client\\loginbutton.jpg"));
		jButton1.setBorder(null);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup()
						.add(59, 59, 59)
						.add(jTextField1,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								155, Short.MAX_VALUE)
						.add(33, 33, 33)
						.add(jButton1,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								127, Short.MAX_VALUE).add(66, 66, 66)));

		layout.setVerticalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(org.jdesktop.layout.GroupLayout.TRAILING,
						layout.createSequentialGroup()
								.add(148, 148, 148)
								.add(layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jButton1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												29,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jTextField1,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												29, Short.MAX_VALUE))
								.add(44, 44, 44)));
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}
